// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.AppUsers;
using ApiSdk.Api.Collections;
using ApiSdk.Api.Custom;
using ApiSdk.Api.Figma;
using ApiSdk.Api.Login;
using ApiSdk.Api.Logout;
using ApiSdk.Api.Onboarding;
using ApiSdk.Api.Projects;
using ApiSdk.Api.Redirect;
using ApiSdk.Api.Register;
using ApiSdk.Api.Unknown;
using ApiSdk.Api.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The appUsers property</summary>
        public global::ApiSdk.Api.AppUsers.AppUsersRequestBuilder AppUsers
        {
            get => new global::ApiSdk.Api.AppUsers.AppUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The collections property</summary>
        public global::ApiSdk.Api.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::ApiSdk.Api.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom property</summary>
        public global::ApiSdk.Api.Custom.CustomRequestBuilder Custom
        {
            get => new global::ApiSdk.Api.Custom.CustomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The figma property</summary>
        public global::ApiSdk.Api.Figma.FigmaRequestBuilder Figma
        {
            get => new global::ApiSdk.Api.Figma.FigmaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::ApiSdk.Api.Login.LoginRequestBuilder Login
        {
            get => new global::ApiSdk.Api.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::ApiSdk.Api.Logout.LogoutRequestBuilder Logout
        {
            get => new global::ApiSdk.Api.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The onboarding property</summary>
        public global::ApiSdk.Api.Onboarding.OnboardingRequestBuilder Onboarding
        {
            get => new global::ApiSdk.Api.Onboarding.OnboardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::ApiSdk.Api.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::ApiSdk.Api.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The redirect property</summary>
        public global::ApiSdk.Api.Redirect.RedirectRequestBuilder Redirect
        {
            get => new global::ApiSdk.Api.Redirect.RedirectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::ApiSdk.Api.Register.RegisterRequestBuilder Register
        {
            get => new global::ApiSdk.Api.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unknown property</summary>
        public global::ApiSdk.Api.Unknown.UnknownRequestBuilder Unknown
        {
            get => new global::ApiSdk.Api.Unknown.UnknownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::ApiSdk.Api.Users.UsersRequestBuilder Users
        {
            get => new global::ApiSdk.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
