// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Onboarding.Complete;
using ApiSdk.Api.Onboarding.Skip;
using ApiSdk.Api.Onboarding.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Onboarding
{
    /// <summary>
    /// Builds and executes requests for operations under \api\onboarding
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OnboardingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The complete property</summary>
        public global::ApiSdk.Api.Onboarding.Complete.CompleteRequestBuilder Complete
        {
            get => new global::ApiSdk.Api.Onboarding.Complete.CompleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skip property</summary>
        public global::ApiSdk.Api.Onboarding.Skip.SkipRequestBuilder Skip
        {
            get => new global::ApiSdk.Api.Onboarding.Skip.SkipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::ApiSdk.Api.Onboarding.Status.StatusRequestBuilder Status
        {
            get => new global::ApiSdk.Api.Onboarding.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Onboarding.OnboardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OnboardingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/onboarding", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Onboarding.OnboardingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OnboardingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/onboarding", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
