// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Figma.Create;
using ApiSdk.Api.Figma.Ingest;
using ApiSdk.Api.Figma.Usage;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Figma
{
    /// <summary>
    /// Builds and executes requests for operations under \api\figma
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FigmaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::ApiSdk.Api.Figma.Create.CreateRequestBuilder Create
        {
            get => new global::ApiSdk.Api.Figma.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ingest property</summary>
        public global::ApiSdk.Api.Figma.Ingest.IngestRequestBuilder Ingest
        {
            get => new global::ApiSdk.Api.Figma.Ingest.IngestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usage property</summary>
        public global::ApiSdk.Api.Figma.Usage.UsageRequestBuilder Usage
        {
            get => new global::ApiSdk.Api.Figma.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Figma.FigmaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FigmaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/figma", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Figma.FigmaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FigmaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/figma", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
