// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

#nullable enable annotations

namespace GeneratedCode
{
    /// <summary>ReqRes API</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IReqResAPI
    {
        /// <summary>List users (legacy)</summary>
        /// <remarks>Retrieve a paginated list of demo users. Supports page/per_page query params.</remarks>
        /// <param name="page">Page number for pagination.</param>
        /// <param name="per_page">Number of users per page.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/users")]
        Task<LegacyUserListResponse> GetLegacyUsers([Query] int? page, [Query] int? per_page);

        /// <summary>Create user (legacy)</summary>
        /// <remarks>Creates a demo user. Returns the request payload plus id/createdAt fields.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>User created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/users")]
        Task<LegacyMutationResponse> CreateLegacyUser([Body] LegacyMutationRequest body);

        /// <summary>Get user by id (legacy)</summary>
        /// <remarks>Retrieve a single demo user by id.</remarks>
        /// <param name="id">User id.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/users/{id}")]
        Task<LegacyUserResponse> GetLegacyUserById(int id);

        /// <summary>Update user (legacy)</summary>
        /// <remarks>Updates a demo user. Returns the request payload plus updatedAt field.</remarks>
        /// <param name="id">User id.</param>
        /// <param name="body">body parameter</param>
        /// <returns>User updated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/users/{id}")]
        Task<LegacyMutationResponse> UpdateLegacyUser(int id, [Body] LegacyMutationRequest body);

        /// <summary>Patch user (legacy)</summary>
        /// <remarks>Partially updates a demo user. Returns the request payload plus updatedAt field.</remarks>
        /// <param name="id">User id.</param>
        /// <param name="body">body parameter</param>
        /// <returns>User updated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/api/users/{id}")]
        Task<LegacyMutationResponse> PatchLegacyUser(int id, [Body] LegacyMutationRequest body);

        /// <summary>Delete user (legacy)</summary>
        /// <remarks>Deletes a demo user and returns no content.</remarks>
        /// <param name="id">User id.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Delete("/api/users/{id}")]
        Task DeleteLegacyUser(int id);

        /// <summary>List resources (legacy)</summary>
        /// <remarks>Retrieve a paginated list of the demo "unknown" resource.</remarks>
        /// <param name="page">Page number for pagination.</param>
        /// <param name="per_page">Number of items per page.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/unknown")]
        Task<LegacyUnknownListResponse> GetLegacyUnknown([Query] int? page, [Query] int? per_page);

        /// <summary>Get resource by id (legacy)</summary>
        /// <remarks>Retrieve a single demo resource by id.</remarks>
        /// <param name="id">Resource id.</param>
        /// <returns>Successful response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/unknown/{id}")]
        Task<LegacyUnknownResponse> GetLegacyUnknownById(int id);

        /// <summary>Register user</summary>
        /// <remarks>Register a demo user account.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Successful registration</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/register")]
        Task<RegisterResponse> RegisterUser([Body] AuthRequest body);

        /// <summary>Login user</summary>
        /// <remarks>Authenticate a demo user and return a token.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Successful login</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/login")]
        Task<LoginResponse> LoginUser([Body] AuthRequest body);

        /// <summary>Logout user</summary>
        /// <remarks>Legacy logout endpoint (returns empty object).</remarks>
        /// <returns>Logged out</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Post("/api/logout")]
        Task<object> LogoutUser();

        /// <summary>Redirect helper</summary>
        /// <remarks>Redirects the client to the provided url query param.</remarks>
        /// <param name="url">Destination URL.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>302</term>
        /// <description>Redirect</description>
        /// </item>
        /// </list>
        /// </exception>
        [Post("/api/redirect")]
        Task RedirectHelper([Query] System.Uri url);

        /// <summary>List collections</summary>
        /// <remarks>List collections for the current project/environment.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <returns>Collections list</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/collections")]
        Task<CollectionListResponse> ListCollections([Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Create collection</summary>
        /// <remarks>Create a new collection.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="body">body parameter</param>
        /// <returns>Collection created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/collections")]
        Task<CollectionResponse> CreateCollection([Body] CollectionCreateRequest body, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Get collection</summary>
        /// <remarks>Fetch a collection by slug.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <returns>Collection</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/collections/{slug}")]
        Task<CollectionResponse> GetCollection(string slug, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Update collection</summary>
        /// <remarks>Update a collection by slug.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <param name="body">body parameter</param>
        /// <returns>Collection updated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/collections/{slug}")]
        Task<CollectionResponse> UpdateCollection(string slug, [Body] CollectionUpdateRequest body, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Delete collection</summary>
        /// <remarks>Delete a collection by slug.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/collections/{slug}")]
        Task DeleteCollection(string slug, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>List records</summary>
        /// <remarks>List records for a collection with filters.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <param name="page">Page number.</param>
        /// <param name="limit">Page size (max 100).</param>
        /// <param name="search">Case-insensitive search on record data.</param>
        /// <param name="created_before">Filter records created before timestamp.</param>
        /// <param name="created_after">Filter records created after timestamp.</param>
        /// <param name="data_contains">JSON string for containment filter.</param>
        /// <param name="order">Sort order by created_at.</param>
        /// <param name="include_deleted">Include soft-deleted records.</param>
        /// <returns>Record list</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/collections/{slug}/records")]
        Task<CollectionRecordListResponse> ListCollectionRecords(string slug, [Query] int? page, [Query] int? limit, [Query] string search, [Query] System.DateTimeOffset? created_before, [Query] System.DateTimeOffset? created_after, [Query] string data_contains, [Query] Order? order, [Query] bool? include_deleted, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Create record</summary>
        /// <remarks>Create a new record in a collection.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <param name="body">body parameter</param>
        /// <returns>Record created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/collections/{slug}/records")]
        Task<CollectionRecordResponse> CreateCollectionRecord(string slug, [Body] CollectionRecordCreateRequest body, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Get record</summary>
        /// <remarks>Fetch a record by id.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <param name="recordId">Record id.</param>
        /// <returns>Record</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/collections/{slug}/records/{recordId}")]
        Task<CollectionRecordResponse> GetCollectionRecord(string slug, string recordId, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Update record</summary>
        /// <remarks>Update a record by id.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <param name="recordId">Record id.</param>
        /// <param name="body">body parameter</param>
        /// <returns>Record updated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/collections/{slug}/records/{recordId}")]
        Task<CollectionRecordResponse> UpdateCollectionRecord(string slug, string recordId, [Body] CollectionRecordUpdateRequest body, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Delete record</summary>
        /// <remarks>Delete a record by id.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="slug">Collection slug.</param>
        /// <param name="recordId">Record id.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/collections/{slug}/records/{recordId}")]
        Task DeleteCollectionRecord(string slug, string recordId, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>App user login (method hint)</summary>
        /// <remarks>Returns a method_not_allowed response with usage guidance.</remarks>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>405</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/app-users/login")]
        Task AppUserLoginMethodHint();

        /// <summary>App user login</summary>
        /// <remarks>Create or log in an app user and send a magic link token.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Login initiated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/app-users/login")]
        Task<AppUserLoginResponse> AppUserLogin([Body] AppUserLoginRequest body);

        /// <summary>Verify app user token</summary>
        /// <remarks>Verify a magic link token and return an app-session token.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Token verified</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/app-users/verify")]
        Task<AppUserVerifyResponse> VerifyAppUserToken([Body] AppUserVerifyRequest body);

        /// <summary>Current app user</summary>
        /// <remarks>Return the current app user based on session token.</remarks>
        /// <returns>App user session</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/app-users/me")]
        Task<AppUserSessionResponse> GetAppUserMe();

        /// <summary>List app users</summary>
        /// <remarks>List app users for the current project.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="limit">Max results (default 50).</param>
        /// <returns>App users list</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/app-users")]
        Task<AppUserListResponse> ListAppUsers([Query] int? limit, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Create app user</summary>
        /// <remarks>Create an app user in the project.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>App user created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/app-users")]
        Task<AppUserResponse> CreateAppUser([Body] AppUserCreateRequest body);

        /// <summary>Get app user</summary>
        /// <remarks>Fetch an app user by id.</remarks>
        /// <param name="id">App user id.</param>
        /// <returns>App user</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/app-users/{id}")]
        Task<AppUserResponse> GetAppUser(string id);

        /// <summary>Update app user</summary>
        /// <remarks>Update an app user by id.</remarks>
        /// <param name="id">App user id.</param>
        /// <param name="body">body parameter</param>
        /// <returns>App user updated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/app-users/{id}")]
        Task<AppUserResponse> UpdateAppUser(string id, [Body] AppUserUpdateRequest body);

        /// <summary>Delete app user</summary>
        /// <remarks>Delete an app user by id.</remarks>
        /// <param name="id">App user id.</param>
        /// <returns>App user deleted</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/app-users/{id}")]
        Task<object> DeleteAppUser(string id);

        /// <summary>Simulate app user session</summary>
        /// <remarks>Owner-only helper to mint an app-user session token.</remarks>
        /// <param name="id">App user id.</param>
        /// <param name="body">body parameter</param>
        /// <returns>Session simulated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/app-users/{id}/sessions/simulate")]
        Task<object> SimulateAppUserSession(string id, [Body] object body);

        /// <summary>List project app users</summary>
        /// <remarks>List app users for a project using API key auth.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="projectId">Project id.</param>
        /// <param name="statuses">Filter by status (active, pending) or use "all".</param>
        /// <returns>App users list</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/projects/{projectId}/app-users")]
        Task<AppUserListResponse> ListProjectAppUsers(string projectId, [Query] string statuses, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>App users total</summary>
        /// <remarks>Return total app user count for a project.</remarks>
        /// <param name="x_Reqres_Env">Environment key (for example: prod or dev).</param>
        /// <param name="projectId">Project id.</param>
        /// <returns>Total count</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/projects/{projectId}/app-users/total")]
        Task<AppUserTotalResponse> GetProjectAppUserTotal(string projectId, [Header("X-Reqres-Env")] string x_Reqres_Env);

        /// <summary>Execute custom endpoint</summary>
        /// <remarks>Execute a custom endpoint with GET.</remarks>
        /// <param name="path">Custom endpoint path (supports nested segments).</param>
        /// <returns>Custom response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/custom/{path}")]
        Task<object> ExecuteCustomEndpointGet(string path);

        /// <summary>Execute custom endpoint</summary>
        /// <remarks>Execute a custom endpoint with POST.</remarks>
        /// <param name="path">Custom endpoint path (supports nested segments).</param>
        /// <param name="body">body parameter</param>
        /// <returns>Custom response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/custom/{path}")]
        Task<object> ExecuteCustomEndpointPost(string path, [Body] object body);

        /// <summary>Execute custom endpoint</summary>
        /// <remarks>Execute a custom endpoint with PUT.</remarks>
        /// <param name="path">Custom endpoint path (supports nested segments).</param>
        /// <param name="body">body parameter</param>
        /// <returns>Custom response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/custom/{path}")]
        Task<object> ExecuteCustomEndpointPut(string path, [Body] object body);

        /// <summary>Execute custom endpoint</summary>
        /// <remarks>Execute a custom endpoint with PATCH.</remarks>
        /// <param name="path">Custom endpoint path (supports nested segments).</param>
        /// <param name="body">body parameter</param>
        /// <returns>Custom response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/api/custom/{path}")]
        Task<object> ExecuteCustomEndpointPatch(string path, [Body] object body);

        /// <summary>Execute custom endpoint</summary>
        /// <remarks>Execute a custom endpoint with DELETE.</remarks>
        /// <param name="path">Custom endpoint path (supports nested segments).</param>
        /// <returns>Custom response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/custom/{path}")]
        Task<object> ExecuteCustomEndpointDelete(string path);

        /// <summary>List templates</summary>
        /// <remarks>Retrieve available backend templates.</remarks>
        /// <param name="category">Filter by template category.</param>
        /// <param name="featured">Filter for featured templates only.</param>
        /// <param name="limit">Maximum templates to return.</param>
        /// <param name="offset">Offset for pagination.</param>
        /// <returns>Templates list</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/templates")]
        Task<TemplatesResponse> GetTemplates([Query] string category, [Query] bool? featured, [Query] int? limit, [Query] int? offset);

        /// <summary>Get template by id</summary>
        /// <remarks>Retrieve a template by id.</remarks>
        /// <param name="id">Template id.</param>
        /// <returns>Template</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/templates/{id}")]
        Task<Template> GetTemplateById(int id);

        /// <summary>Onboarding status</summary>
        /// <remarks>Return onboarding status for the authenticated user.</remarks>
        /// <returns>Status response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/onboarding/status")]
        Task<object> GetOnboardingStatus();

        /// <summary>Complete onboarding</summary>
        /// <remarks>Mark onboarding as complete.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Onboarding completed</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/onboarding/complete")]
        Task<object> CompleteOnboarding([Body] object body);

        /// <summary>Skip onboarding</summary>
        /// <remarks>Mark onboarding as skipped.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Onboarding skipped</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/onboarding/skip")]
        Task<object> SkipOnboarding([Body] object body);

        /// <summary>Figma ingest</summary>
        /// <remarks>Ingest Figma payloads for API generation.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Ingested</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/figma/ingest")]
        Task<object> FigmaIngest([Body] object body);

        /// <summary>Figma create</summary>
        /// <remarks>Create backend resources from a Figma payload.</remarks>
        /// <param name="body">body parameter</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/figma/create")]
        Task<object> FigmaCreate([Body] object body);

        /// <summary>Figma usage</summary>
        /// <remarks>Return Figma integration usage for the user.</remarks>
        /// <returns>Usage response</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/figma/usage")]
        Task<object> FigmaUsage();

        /// <summary>App user profile</summary>
        /// <remarks>Return app-user profile from a session token.</remarks>
        /// <returns>App user profile</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/app/me")]
        Task<AppUserSessionResponse> GetAppSessionProfile();

        /// <summary>List collections (app user)</summary>
        /// <remarks>List collections with an app-user session token.</remarks>
        /// <returns>Collections list</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/app/collections")]
        Task<CollectionListResponse> ListCollectionsAppUser();

        /// <summary>Get collection (app user)</summary>
        /// <remarks>Fetch collection by slug with an app-user token.</remarks>
        /// <param name="slug">Collection slug.</param>
        /// <returns>Collection</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/app/collections/{slug}")]
        Task<CollectionResponse> GetCollectionAppUser(string slug);

        /// <summary>List records (app user)</summary>
        /// <remarks>List records with an app-user token.</remarks>
        /// <param name="slug">Collection slug.</param>
        /// <returns>Records</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/app/collections/{slug}/records")]
        Task<CollectionRecordListResponse> ListRecordsAppUser(string slug);

        /// <summary>Create record (app user)</summary>
        /// <remarks>Create a record with an app-user token.</remarks>
        /// <param name="slug">Collection slug.</param>
        /// <param name="body">body parameter</param>
        /// <returns>Record created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/app/collections/{slug}/records")]
        Task<CollectionRecordResponse> CreateRecordAppUser(string slug, [Body] CollectionRecordCreateRequest body);

        /// <summary>Get record (app user)</summary>
        /// <remarks>Fetch a record by id with an app-user token.</remarks>
        /// <param name="slug">Collection slug.</param>
        /// <param name="recordId">Record id.</param>
        /// <returns>Record</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/app/collections/{slug}/records/{recordId}")]
        Task<CollectionRecordResponse> GetRecordAppUser(string slug, string recordId);

        /// <summary>Update record (app user)</summary>
        /// <remarks>Update a record with an app-user token.</remarks>
        /// <param name="slug">Collection slug.</param>
        /// <param name="recordId">Record id.</param>
        /// <param name="body">body parameter</param>
        /// <returns>Record updated</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/app/collections/{slug}/records/{recordId}")]
        Task<CollectionRecordResponse> UpdateRecordAppUser(string slug, string recordId, [Body] CollectionRecordUpdateRequest body);

        /// <summary>Delete record (app user)</summary>
        /// <remarks>Delete a record with an app-user token.</remarks>
        /// <param name="slug">Collection slug.</param>
        /// <param name="recordId">Record id.</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Error response</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/app/collections/{slug}/records/{recordId}")]
        Task DeleteRecordAppUser(string slug, string recordId);


    }

}

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace GeneratedCode
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ErrorResponse
    {

        [JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; }

        [JsonPropertyName("message")]
        public string Message { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyUser
    {

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        [JsonPropertyName("first_name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string FirstName { get; set; }

        [JsonPropertyName("last_name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string LastName { get; set; }

        [JsonPropertyName("avatar")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Avatar { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyUserListResponse
    {

        [JsonPropertyName("page")]
        public int Page { get; set; }

        [JsonPropertyName("per_page")]
        public int PerPage { get; set; }

        [JsonPropertyName("total")]
        public int Total { get; set; }

        [JsonPropertyName("total_pages")]
        public int TotalPages { get; set; }

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<LegacyUser> Data { get; set; } = new System.Collections.ObjectModel.Collection<LegacyUser>();

        [JsonPropertyName("support")]
        public object Support { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyUserResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public LegacyUser Data { get; set; } = new LegacyUser();

        [JsonPropertyName("support")]
        public object Support { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyMutationRequest
    {

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyMutationResponse
    {

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("createdAt")]
        public System.DateTimeOffset CreatedAt { get; set; }

        [JsonPropertyName("updatedAt")]
        public System.DateTimeOffset UpdatedAt { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyUnknown
    {

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [JsonPropertyName("year")]
        public int Year { get; set; }

        [JsonPropertyName("color")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Color { get; set; }

        [JsonPropertyName("pantone_value")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PantoneValue { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyUnknownListResponse
    {

        [JsonPropertyName("page")]
        public int Page { get; set; }

        [JsonPropertyName("per_page")]
        public int PerPage { get; set; }

        [JsonPropertyName("total")]
        public int Total { get; set; }

        [JsonPropertyName("total_pages")]
        public int TotalPages { get; set; }

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<LegacyUnknown> Data { get; set; } = new System.Collections.ObjectModel.Collection<LegacyUnknown>();

        [JsonPropertyName("support")]
        public object Support { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LegacyUnknownResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public LegacyUnknown Data { get; set; } = new LegacyUnknown();

        [JsonPropertyName("support")]
        public object Support { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AuthRequest
    {

        [JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        [JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Password { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RegisterResponse
    {

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("token")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginResponse
    {

        [JsonPropertyName("token")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Collection
    {

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [JsonPropertyName("project_id")]
        public string ProjectId { get; set; }

        [JsonPropertyName("user_id")]
        public string UserId { get; set; }

        [JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [JsonPropertyName("slug")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Slug { get; set; }

        [JsonPropertyName("schema")]
        public object Schema { get; set; }

        [JsonPropertyName("visibility")]
        public string Visibility { get; set; }

        [JsonPropertyName("created_at")]
        public System.DateTimeOffset CreatedAt { get; set; }

        [JsonPropertyName("updated_at")]
        public System.DateTimeOffset UpdatedAt { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionListResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<Collection> Data { get; set; } = new System.Collections.ObjectModel.Collection<Collection>();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public Collection Data { get; set; } = new Collection();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionCreateRequest
    {

        [JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        [JsonPropertyName("schema")]
        public object Schema { get; set; }

        [JsonPropertyName("project_id")]
        public string ProjectId { get; set; }

        [JsonPropertyName("visibility")]
        public string Visibility { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionUpdateRequest
    {

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        [JsonPropertyName("schema")]
        public object Schema { get; set; }

        [JsonPropertyName("visibility")]
        public string Visibility { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionRecord
    {

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [JsonPropertyName("collection_id")]
        public string CollectionId { get; set; }

        [JsonPropertyName("project_id")]
        public string ProjectId { get; set; }

        [JsonPropertyName("app_user_id")]
        public string AppUserId { get; set; }

        [JsonPropertyName("created_by")]
        public string CreatedBy { get; set; }

        [JsonPropertyName("created_at")]
        public System.DateTimeOffset CreatedAt { get; set; }

        [JsonPropertyName("updated_at")]
        public System.DateTimeOffset UpdatedAt { get; set; }

        [JsonPropertyName("deleted_at")]
        public System.DateTimeOffset? DeletedAt { get; set; }

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Data { get; set; } = new object();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionRecordListResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<CollectionRecord> Data { get; set; } = new System.Collections.ObjectModel.Collection<CollectionRecord>();

        [JsonPropertyName("meta")]
        public Meta Meta { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionRecordResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public CollectionRecord Data { get; set; } = new CollectionRecord();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionRecordCreateRequest
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Data { get; set; } = new object();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectionRecordUpdateRequest
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Data { get; set; } = new object();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUser
    {

        [JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }

        [JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("last_login_at")]
        public System.DateTimeOffset LastLoginAt { get; set; }

        [JsonPropertyName("created_at")]
        public System.DateTimeOffset CreatedAt { get; set; }

        [JsonPropertyName("metadata")]
        public object Metadata { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserListResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public ICollection<AppUser> Data { get; set; } = new System.Collections.ObjectModel.Collection<AppUser>();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public AppUser Data { get; set; } = new AppUser();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserLoginRequest
    {

        [JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        [JsonPropertyName("project_id")]
        public string ProjectId { get; set; }

        [JsonPropertyName("metadata")]
        public object Metadata { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserLoginResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Data { get; set; } = new object();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserVerifyRequest
    {

        [JsonPropertyName("token")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserVerifyResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Data { get; set; } = new object();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserCreateRequest
    {

        [JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Email { get; set; }

        [JsonPropertyName("metadata")]
        public object Metadata { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserUpdateRequest
    {

        [JsonPropertyName("email")]
        public string Email { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("metadata")]
        public object Metadata { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserSessionResponse
    {

        [JsonPropertyName("data")]
        [System.ComponentModel.DataAnnotations.Required]
        public object Data { get; set; } = new object();

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppUserTotalResponse
    {

        [JsonPropertyName("total")]
        public int Total { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Template
    {

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        [JsonPropertyName("category")]
        public string Category { get; set; }

        [JsonPropertyName("icon")]
        public string Icon { get; set; }

        [JsonPropertyName("is_featured")]
        public bool IsFeatured { get; set; }

        [JsonPropertyName("config")]
        public object Config { get; set; }

        [JsonPropertyName("endpoints")]
        public ICollection<object> Endpoints { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TemplatesResponse
    {

        [JsonPropertyName("templates")]
        public ICollection<Template> Templates { get; set; }

        [JsonPropertyName("pagination")]
        public Pagination Pagination { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Order
    {

        [System.Runtime.Serialization.EnumMember(Value = @"asc")]
        Asc = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"desc")]
        Desc = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Meta
    {

        [JsonPropertyName("page")]
        public int Page { get; set; }

        [JsonPropertyName("limit")]
        public int Limit { get; set; }

        [JsonPropertyName("total")]
        public int Total { get; set; }

        [JsonPropertyName("pages")]
        public int Pages { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Pagination
    {

        [JsonPropertyName("total")]
        public int Total { get; set; }

        [JsonPropertyName("limit")]
        public int Limit { get; set; }

        [JsonPropertyName("offset")]
        public int Offset { get; set; }

        [JsonPropertyName("pages")]
        public int Pages { get; set; }

        private IDictionary<string, object> _additionalProperties;

        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765