// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Projects.Item.AppUsers.Total;
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Api.Projects.Item.AppUsers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\projects\{projectId}\app-users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppUsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The total property</summary>
        public global::ApiSdk.Api.Projects.Item.AppUsers.Total.TotalRequestBuilder Total
        {
            get => new global::ApiSdk.Api.Projects.Item.AppUsers.Total.TotalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppUsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/app-users{?statuses*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppUsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/projects/{projectId}/app-users{?statuses*}", rawUrl)
        {
        }
        /// <summary>
        /// List app users for a project using API key auth.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.AppUserListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.ErrorResponse">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.AppUserListResponse?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder.AppUsersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.AppUserListResponse> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder.AppUsersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::ApiSdk.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.AppUserListResponse>(requestInfo, global::ApiSdk.Models.AppUserListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List app users for a project using API key auth.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder.AppUsersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder.AppUsersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List app users for a project using API key auth.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AppUsersRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by status (active, pending) or use &quot;all&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("statuses")]
            public string? Statuses { get; set; }
#nullable restore
#else
            [QueryParameter("statuses")]
            public string Statuses { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AppUsersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Projects.Item.AppUsers.AppUsersRequestBuilder.AppUsersRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
