// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.AppUsers.Item.Sessions.Simulate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.AppUsers.Item.Sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\app-users\{id}\sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The simulate property</summary>
        public global::ApiSdk.Api.AppUsers.Item.Sessions.Simulate.SimulateRequestBuilder Simulate
        {
            get => new global::ApiSdk.Api.AppUsers.Item.Sessions.Simulate.SimulateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.AppUsers.Item.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/app-users/{id}/sessions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.AppUsers.Item.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/app-users/{id}/sessions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
